builders:
  glew_partgen:
    import: "package:glew/glew.dart"
    builder_factories: ["trackableStateBuilder"]
    build_extensions: {".dart": ["glew.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      glew|glew_partgen:
        generate_for:
          - lib/**