name: glew
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  source_gen: ^2.0.0
  analyzer: ^7.4.4
  build: ^2.4.1
  socket_io_client: ^3.1.1
  sane_uuid: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.7
  build_test: ^2.2.3
  json_serializable: ^6.9.5
